# Generated by Django 4.0.4 on 2022-04-19 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0002_alter_recurso_options_alter_recurso_data_alocacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
