# Generated by Django 4.0.4 on 2022-04-21 00:14

from django.db import migrations, models
import recursos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_alter_alocacao_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='data_alocacao',
            field=models.DateField(validators=[recursos.validators.validatar_data_futuro]),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('A', 'Alocado')], default='D', max_length=1),
        ),
    ]
