# Generated by Django 4.0.4 on 2022-04-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_alter_alocacao_data_alocacao_alter_recurso_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível')], default='D', max_length=1),
        ),
    ]
