# Generated by Django 4.0.4 on 2022-04-21 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0007_alter_recurso_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='data_maxima_alocacao',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurso',
            name='periodo_maximo_alocacao',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='alocador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='recursos.recurso'),
        ),
    ]
